# Generated by Django 5.1.3 on 2025-08-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={},
        ),
        migrations.RemoveField(
            model_name="activity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("Running", "Running"),
                    ("Cycling", "Cycling"),
                    ("Weightlifting", "Weightlifting"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="calories_burned",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
